// This file will be auto-generated by Supabase CLI
// Run: npm run generate-types from packages/database directory
// after setting up your Supabase project

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          created_at?: string
          updated_at?: string
        }
      }
      properties: {
        Row: {
          id: string
          user_id: string
          address: string
          parcel_number: string | null
          assessed_value: number
          market_value: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          address: string
          parcel_number?: string | null
          assessed_value: number
          market_value?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          address?: string
          parcel_number?: string | null
          assessed_value?: number
          market_value?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      appeals: {
        Row: {
          id: string
          property_id: string
          user_id: string
          status: 'draft' | 'submitted' | 'pending' | 'approved' | 'rejected'
          estimated_savings: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          property_id: string
          user_id: string
          status?: 'draft' | 'submitted' | 'pending' | 'approved' | 'rejected'
          estimated_savings?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          property_id?: string
          user_id?: string
          status?: 'draft' | 'submitted' | 'pending' | 'approved' | 'rejected'
          estimated_savings?: number | null
          created_at?: string
          updated_at?: string
        }
      }
    }
  }
}